### ISSUE TITLE
Not work require().default

### ISSUE THREAD

**Issue by den67rus** [intoli/user-agents#10]
I use typescript and get this error:
```
const userAgent = new user_agents_1.default();
                  ^
TypeError: user_agents_1.default is not a constructor
    at Object.<anonymous> (C:\Users\user\Desktop\new\sdfsdf.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)
    at internal/main/run_main_module.js:17:11
```
code before compilation:
```
import UserAgent from 'user-agents';

const userAgent = new UserAgent();
console.log(userAgent.toString()); //
console.log(JSON.stringify(userAgent.data, null, 2));
```
code after compilation typescript:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const user_agents_1 = require("user-agents");
const userAgent = new user_agents_1.default();
console.log(userAgent.toString()); //
console.log(JSON.stringify(userAgent.data, null, 2));
```

I think it has something to do with: https://github.com/babel/babel/issues/2212

I think this can be fixed using the plugin https://www.npmjs.com/package/babel-plugin-add-module-exports with a parameter `addDefaultProperty`

**Comment by den67rus** [comment]
Decision:
```
import * as UserAgent from 'user-agents';

const userAgent = new UserAgent();
console.log(userAgent.toString()); //
console.log(JSON.stringify(userAgent.data, null, 2));
```
